#!/bin/bash

# Script para monitorar logs de redirecionamento
# Execute: chmod +x debug-redirect.sh && ./debug-redirect.sh

echo "🔍 MONITORAMENTO DE REDIRECIONAMENTOS ATIVO"
echo "================================================"
echo ""
echo "📋 LOGS PARA PROCURAR:"
echo "🔐 [AdminProtectedRoute] - Logs do componente AdminProtectedRoute"
echo "🔐 [ProtectedRoute] - Logs do componente ProtectedRoute genérico"
echo "🚪 [useAuth] - Logs do hook useAuth"
echo ""
echo "❌ Redirecionamentos por falta de token"
echo "⏰ Redirecionamentos por token expirado"
echo "💥 Redirecionamentos por erro de validação"
echo "🔄 Mudanças no localStorage"
echo ""
echo "================================================"
echo "💡 DICAS DE DEBUG:"
echo ""
echo "1. Abra o DevTools (F12)"
echo "2. Vá para a aba Console"
echo "3. Filtre por 'ProtectedRoute' ou 'useAuth'"
echo "4. Acesse /admin/login no seu ambiente de produção"
echo "5. Observe a sequência de logs"
echo ""
echo "🎯 O QUE PROCURAR:"
echo "- Se está usando ProtectedRoute ou AdminProtectedRoute"
echo "- Qual token está sendo encontrado (admin_token vs token)"
echo "- Para qual rota está redirecionando"
echo "- Se o token está válido ou expirado"
echo ""
echo "📝 CENÁRIOS POSSÍVEIS:"
echo ""
echo "Cenário 1: Sem token"
echo "  -> Deve redirecionar para /admin/login"
echo ""
echo "Cenário 2: Com token normal em rota admin"
echo "  -> Deve redirecionar para /admin/login"
echo ""
echo "Cenário 3: Com admin_token válido"
echo "  -> Deve permitir acesso à rota admin"
echo ""
echo "Cenário 4: Com admin_token expirado"
echo "  -> Deve limpar token e redirecionar para /admin/login"
echo ""
echo "================================================"
echo "🚀 Agora acesse sua aplicação e monitore os logs!"
